<?php

if (!defined('ABSPATH')) exit;


$elfsight_yottie_defaults = array(
	// SOURCE
	'channel' => null,
	'source_groups' => null,
	'cache_time' => 3600,

	// SIZES
	'width' => 'auto',

	// LANGUAGE
	'lang' => 'en',
	
	// HEADER
	'header_visible' => true,
	'header_layout' => 'classic',
	'header_info' => 'logo, banner, channelName, channelDescription, videosCounter, subscribersCounter, viewsCounter, subscribeButton',
	'header_channel_name' => '',
	'header_channel_description' => '',
	'header_channel_logo' => '',
	'header_channel_banner' => '',

	// GROUPS
	'groups_visible' => true,

	// CONTENT
	'content_columns' => 3,
	'content_rows' => 1,
	'content_gutter' => 20,
	'content_arrows_control' => true,
	'content_scroll_control' => false,
	'content_drag_control' => true,
	//'content_direction' => 'horizontal',
	'content_free_mode' => false,
	'content_scrollbar' => false,
	'content_transition_effect' => 'slide',
	'content_transition_speed' => 600,
	//'content_transition_easing' => 'ease',
	'content_auto' => 0,
	'content_auto_pause_on_hover' => false,
	'content_responsive' => null,

	// VIDEO
	'video_layout' => 'classic',
	'video_info' => 'playIcon, duration, title, date, description, viewsCounter, likesCounter, commentsCounter',
	'video_play_mode' => 'popup',

	// POPUP
	'popup_info' => 'title, channelLogo, channelName, subscribeButton, viewsCounter, likesCounter, dislikesCounter, likesRatio, date, description, descriptionMoreButton, comments',
	'popup_autoplay' => true,
	//'popup_transition_speed' => 600,
	//'popup_transition_easing' => 'ease',

	// COLORS
	'color_scheme' => 'default',
	'color_header_bg' => null,
	'color_header_banner_overlay' => null,
	'color_header_channel_name' => null,
	'color_header_channel_name_hover' => null,
	'color_header_channel_description' => null,
	'color_header_counters' => null,

	'color_groups_bg' => null,
	'color_groups_link' => null,
	'color_groups_link_hover' => null,
	'color_groups_link_active' => null,
	'color_groups_highlight' => null,
	'color_groups_highlight_hover' => null,
	'color_groups_highlight_active' => null,

	'color_content_bg' => null,
	'color_content_arrows' => null,
	'color_content_arrows_hover' => null,
	'color_content_arrows_bg' => null,
	'color_content_arrows_bg_hover' => null,
	'color_content_scrollbar_bg' => null,
	'color_content_scrollbar_slider_bg' => null,

	'color_video_bg' => null,
	'color_video_overlay' => null,
	'color_video_play_icon' => null,
	'color_video_play_icon_hover' => null,
	'color_video_duration' => null,
	'color_video_duration_bg' => null,
	'color_video_title' => null,
	'color_video_title_hover' => null,
	'color_video_anchor' => null,
	'color_video_anchor_hover' => null,
	'color_video_date' => null,
	'color_video_description' => null,
	'color_video_counters' => null,

	'color_popup_bg' => null,
	'color_popup_anchor' => null,
	'color_popup_anchor_hover' => null,
	'color_popup_overlay' => null,
	'color_popup_title' => null,
	'color_popup_channel_name' => null,
	'color_popup_channel_name_hover' => null,
	'color_popup_views_counter' => null,
	'color_popup_likes_ratio' => null,
	'color_popup_dislikes_ratio' => null,
	'color_popup_likes_counter' => null,
	'color_popup_dislikes_counter' => null,
	'color_popup_date' => null,
	'color_popup_description' => null,
	'color_popup_description_more_button' => null,
	'color_popup_description_more_button_hover' => null,
	'color_popup_comments_username' => null,
	'color_popup_comments_username_hover' => null,
	'color_popup_comments_passed_time' => null,
	'color_popup_comments_text' => null,
	'color_popup_comments_likes' => null,
	'color_popup_controls' => null,
	'color_popup_controls_hover' => null,
	'color_popup_controls_mobile' => null,
	'color_popup_controls_mobile_bg' => null
);

$elfsight_yottie_color_schemes = array(
	'default' => array(
		'color_header_bg' => 'rgb(255, 255, 255)',
		'color_header_banner_overlay' => 'rgba(255, 255, 255, 0.81)',
		'color_header_channel_name' => 'rgb(34, 34, 34)',
		'color_header_channel_name_hover' => 'rgb(47, 165, 255)',
		'color_header_channel_description' => 'rgb(34, 34, 34)',
		'color_header_counters' => 'rgb(102, 102, 102)',

		'color_groups_bg' => 'rgb(255, 255, 255)',
		'color_groups_link' => 'rgb(34, 34, 34)',
		'color_groups_link_hover' => 'rgb(255, 0, 0)',
		'color_groups_link_active' => 'rgb(255, 0, 0)',
		'color_groups_highlight' => 'rgb(204, 204, 204)',
		'color_groups_highlight_hover' => 'rgb(255, 0, 0)',
		'color_groups_highlight_active' => 'rgb(255, 0, 0)',

		'color_content_bg' => 'rgb(255, 255, 255)',
		'color_content_arrows' => 'rgb(255, 255, 255)',
		'color_content_arrows_hover' => 'rgb(255, 0, 0)',
		'color_content_arrows_bg' => 'rgba(0, 0, 0, 0.4)',
		'color_content_arrows_bg_hover' => 'rgba(0, 0, 0, 0.8)',
		'color_content_scrollbar_bg' => 'rgb(204, 204, 204)',
		'color_content_scrollbar_slider_bg' => 'rgba(0, 0, 0, 0.4)',

		'color_video_bg' => 'rgb(243, 243, 243)',
		'color_video_overlay' => 'rgba(255, 255, 255, 0.9)',
		'color_video_play_icon' => 'rgba(255, 255, 255, 0.4)',
		'color_video_play_icon_hover' => 'rgba(255, 255, 255, 0.8)',
		'color_video_duration' => 'rgb(255, 255, 255)',
		'color_video_duration_bg' => 'rgba(34, 34, 34, 0.81)',
		'color_video_title' => 'rgb(26, 137, 222)',
		'color_video_title_hover' => 'rgb(47, 165, 255)',
		'color_video_date' => 'rgb(140, 140, 140)',
		'color_video_description' => 'rgb(34, 34, 34)',
		'color_video_anchor' => 'rgb(26, 137, 222)',
		'color_video_anchor_hover' => 'rgb(47, 165, 255)',
		'color_video_counters' => 'rgb(149, 149, 149)',

		'color_popup_bg' => 'rgb(255, 255, 255)',
		'color_popup_anchor' => 'rgb(26, 137, 222)',
		'color_popup_anchor_hover' => 'rgb(47, 165, 255)',
		'color_popup_overlay' => 'rgba(0, 0, 0, 0.7)',
		'color_popup_title' => 'rgb(34, 34, 34)',
		'color_popup_channel_name' => 'rgb(34, 34, 34)',
		'color_popup_channel_name_hover' => 'rgb(47, 165, 255)',
		'color_popup_views_counter' => 'rgb(85, 85, 85)',
		'color_popup_likes_ratio' => 'rgb(47, 165, 255)',
		'color_popup_dislikes_ratio' => 'rgb(207, 207, 207)',
		'color_popup_likes_counter' => 'rgb(144, 144, 144)',
		'color_popup_dislikes_counter' => 'rgb(144, 144, 144)',
		'color_popup_date' => 'rgb(34, 34, 34)',
		'color_popup_description' => 'rgb(34, 34, 34)',
		'color_popup_description_more_button' => 'rgb(102, 102, 102)',
		'color_popup_description_more_button_hover' => 'rgb(34, 34, 34)',
		'color_popup_comments_username' => 'rgb(34, 34, 34)',
		'color_popup_comments_username_hover' => 'rgb(47, 165, 255)',
		'color_popup_comments_passed_time' => 'rgb(115, 115, 115)',
		'color_popup_comments_text' => 'rgb(34, 34, 34)',
		'color_popup_comments_likes' => 'rgb(180, 180, 180)',
		'color_popup_controls' => 'rgb(160, 160, 160)',
		'color_popup_controls_hover' => 'rgb(220, 220, 220)',
		'color_popup_controls_mobile' => 'rgb(220, 220, 220)',
		'color_popup_controls_mobile_bg' => 'rgba(255, 255, 255, 0)'
	),
	'dark' => array(
		'color_header_bg' => 'rgb(51, 51, 51)',
		'color_header_banner_overlay' => 'rgba(51, 51, 51, 0.81)',
		'color_header_channel_name' => 'rgb(255, 255, 255)',
		'color_header_channel_name_hover' => 'rgb(77, 178, 255)',
		'color_header_channel_description' => 'rgb(255, 255, 255)',
		'color_header_counters' => 'rgb(160, 160, 160)',

		'color_groups_bg' => 'rgb(51, 51, 51)',
		'color_groups_link' => 'rgb(255, 255, 255)',
		'color_groups_link_hover' => 'rgb(255, 66, 66)',
		'color_groups_link_active' => 'rgb(255, 66, 66)',
		'color_groups_highlight' => 'rgb(85, 85, 85)',
		'color_groups_highlight_hover' => 'rgb(255, 66, 66)',
		'color_groups_highlight_active' => 'rgb(255, 66, 66)',

		'color_content_bg' => 'rgb(51, 51, 51)',
		'color_content_arrows' => 'rgb(34, 34, 34)',
		'color_content_arrows_hover' => 'rgb(255, 0, 0)',
		'color_content_arrows_bg' => 'rgba(255, 255, 255, 0.4)',
		'color_content_arrows_bg_hover' => 'rgba(255, 255, 255, 0.8)',
		'color_content_scrollbar_bg' => 'rgb(85, 85, 85)',
		'color_content_scrollbar_slider_bg' => 'rgba(255, 255, 255, 0.4)',

		'color_video_bg' => 'rgb(28, 28, 28)',
		'color_video_overlay' => 'rgba(28, 28, 28, 0.9)',
		'color_video_play_icon' => 'rgba(255, 255, 255, 0.4)',
		'color_video_play_icon_hover' => 'rgba(255, 255, 255, 0.8)',
		'color_video_duration' => 'rgb(255, 255, 255)',
		'color_video_duration_bg' => 'rgba(28, 28, 28, 0.81)',
		'color_video_title' => 'rgb(42, 163, 255)',
		'color_video_title_hover' => 'rgb(77, 178, 255)',
		'color_video_date' => 'rgb(116, 116, 116)',
		'color_video_description' => 'rgb(200, 200, 200)',
		'color_video_anchor' => 'rgb(42, 163, 255)',
		'color_video_anchor_hover' => 'rgb(77, 178, 255)',
		'color_video_counters' => 'rgb(112, 112, 112)',

		'color_popup_bg' => 'rgb(51, 51, 51)',
		'color_popup_anchor' => 'rgb(42, 163, 255)',
		'color_popup_anchor_hover' => 'rgb(77, 178, 255)',
		'color_popup_overlay' => 'rgba(0, 0, 0, 0.7)',
		'color_popup_title' => 'rgb(255, 255, 255)',
		'color_popup_channel_name' => 'rgb(255, 255, 255)',
		'color_popup_channel_name_hover' => 'rgb(77, 178, 255)',
		'color_popup_views_counter' => 'rgb(255, 255, 255)',
		'color_popup_likes_ratio' => 'rgb(47, 165, 255)',
		'color_popup_dislikes_ratio' => 'rgb(100, 100, 100)',
		'color_popup_likes_counter' => 'rgb(144, 144, 144)',
		'color_popup_dislikes_counter' => 'rgb(144, 144, 144)',
		'color_popup_date' => 'rgb(255, 255, 255)',
		'color_popup_description' => 'rgb(255, 255, 255)',
		'color_popup_description_more_button' => 'rgb(120, 120, 120)',
		'color_popup_description_more_button_hover' => 'rgb(255, 255, 255)',
		'color_popup_comments_username' => 'rgb(255, 255, 255)',
		'color_popup_comments_username_hover' => 'rgb(77, 178, 255)',
		'color_popup_comments_passed_time' => 'rgb(116, 116, 116)',
		'color_popup_comments_text' => 'rgb(255, 255, 255)',
		'color_popup_comments_likes' => 'rgb(116, 116, 116)',
		'color_popup_controls' => 'rgb(160, 160, 160)',
		'color_popup_controls_hover' => 'rgb(220, 220, 220)',
		'color_popup_controls_mobile' => 'rgb(220, 220, 220)',
		'color_popup_controls_mobile_bg' => 'rgba(255, 255, 255, 0)'
	)
);

$elfsight_yottie_add_scripts = false;

?>